test: fix AKS version in e2e test (#1706)
**Reason for Change**:
<!-- What does this PR improve or fix in KAITO? Why is it needed? -->
test: fix AKS version in e2e test, `--kubernetes-version 1.31.10` is not
supported any more

```
Run if [ "gpuprovisioner" == "gpuprovisioner" ]; then
az aks create  --name kaitori20388204063rn10ra1 --resource-group kaitori20388204063rn10ra1 \
--location swedencentral --attach-acr kaitori20388204063rn10ra1 \
--kubernetes-version 1.31.10 --generate-ssh-keys  \
--enable-managed-identity --enable-workload-identity --enable-oidc-issuer --node-vm-size Standard_D2d_v4 -o none
ERROR: (K8sVersionNotSupported) Managed cluster kaitori20388204063rn10ra1 is on version 1.31.10, which is only available for Long-Term Support (LTS). If you intend to onboard to LTS, please ensure the cluster is in Premium tier and LTS support plan (see https://aka.ms/aks/enable-lts). Otherwise, use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list
Code: K8sVersionNotSupported
Message: Managed cluster kaitori20388204063rn10ra1 is on version 1.31.10, which is only available for Long-Term Support (LTS). If you intend to onboard to LTS, please ensure the cluster is in Premium tier and LTS support plan (see https://aka.ms/aks/enable-lts). Otherwise, use [az aks get-versions] command to get the supported version list in this region. For more information, please check https://aka.ms/supported-version-list
```

**Requirements**

- [x] added unit tests and e2e tests (if applicable).

**Issue Fixed**:
<!-- If this PR fixes GitHub issue 4321, add "Fixes #4321" to the next
line. -->

**Notes for Reviewers**: